### PR TITLE
LANG: more pkgdata updates

### PR DESCRIPTION
**Pull request by lizgehret**
Hey @misialq,

Sorry for inundating you with more PRs! These test failures didn't show up from the last paired PR I opened, which is a bit strange. I double checked the head ref for the main branch on moshpit, and it coincides with the merge commit from the PR I'd opened last week... so we should have seen these failures show up prior to merging that PR. In any case, I'm opening up another PR in distributions to test this, and then hopefully we should see a passing metagenome environment!

**EDIT**: paired PR in distributions: https://github.com/qiime2/distributions/pull/299

### CODE REVIEW

**Comment by lizgehret** [comment]
PR in distributions is passing! Would you mind merging this when you get the chance @misialq?

**Review by ebolyen — APPROVED** [review]

**Comment by lizgehret** [comment]
\q2ci

**Comment by lizgehret** [comment]
Hey @misialq! I discussed this with @ebolyen and the reason that additional test failures were found when I opened up that PR in distributions (after you'd merged [this PR in moshpit](https://github.com/bokulich-lab/q2-moshpit/pull/188)) was essentially from unlucky timing. When that PR got merged, it's parent commit was [this one](https://github.com/bokulich-lab/q2-moshpit/commit/0d0753b279f329d55d6d64399f4aee6e94bf02e1) - which coincided to the hmmer changes that occurred [here](https://github.com/bokulich-lab/q2-moshpit/commit/0d0753b279f329d55d6d64399f4aee6e94bf02e1) (even though they technically got merged prior to my PR). In any case, this current PR that's open addresses additional pkg data paths that were missing from https://github.com/bokulich-lab/q2-moshpit/pull/184 - so this should hopefully be the last PR to fix the failing metagenome build! 😅

**Pull request merged**
