### PR TITLE
LANG: updating pkg data dirs to fix metagenome prepare failures

### PR DESCRIPTION
**Pull request by lizgehret**
Original PR with details: https://github.com/bokulich-lab/q2-moshpit/pull/187
Linked PR in distributions: https://github.com/qiime2/distributions/pull/290

### CODE REVIEW

**Review by misialq — APPROVED** [review]
Hey @lizgehret, thanks for the PR! Should I just merge this or is there still anything else to be done here or elsewhere?

**Comment by lizgehret** [comment]
Hey @misialq! I think there are still a few paths that are missing - the paired PR over in distributions still isn't passing. I'm about to head out for the holiday weekend, but I'll take another look when I'm back next week!

**Comment by misialq** [comment]
Sure thing! Enjoy your holiday! 👋

**Comment by lizgehret** [comment]
Things are looking good so far, I think I've got the last of the failures sorted - just running the prepare one last time to confirm and then I think we'll be good to merge this @misialq!

**Comment by lizgehret** [comment]
Latest changes were successful @misialq, you are good to merge this whenever you get the chance!

**Pull request merged**
